Airlines.Web/Models/ErrorViewModel.cs
namespace Airlines.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Airlines.Web/Models/IndexViewModel.cs
namespace Airlines.Web.Models;

public class IndexViewModel
{
    public int AirlinesCount { get; set; }
    public int AirportsCount { get; set; }
    public int FlightsCount { get; set; }

}

Airlines.Web/Controllers/AirlineController.cs
using Microsoft.AspNetCore.Mvc;

using AirlinesWebServices.Models;
using AirlinesWebServices.Services;

namespace AirlinesWebServices.Controllers;
public class AirlineController : Controller
{
    private readonly IAirlineService _airlineService;
    public AirlineController(IAirlineService airlineService)
    {
        _airlineService = airlineService;
    }
    // GET: AirlineController
    public ActionResult Index(string searchTerm, string selectedOption)
    {
        try
        {
            if (!string.IsNullOrEmpty(searchTerm) && !string.IsNullOrEmpty(selectedOption))
            {
                List<Airline> airlines = _airlineService.GetAirlinesByFilter(searchTerm, selectedOption);
                return View(airlines);
            }
            else
            {
                List<Airline> airlines = _airlineService.GetAirlines();
                return View(airlines);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(new List<Airline>());
        }
    }

    [HttpPost]
    public ActionResult Index(Airline airline)
    {
        try
        {
            _airlineService.AddAirline(airline);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(nameof(Index));
        }
    }

    public ActionResult Search()
    {
        return PartialView();
    }
}

Airlines.Web/Controllers/AirportController.cs
using Microsoft.AspNetCore.Mvc;

using AirlinesWebServices.Services;
using Airport = AirlinesWebServices.Models.Airport;

namespace AirlinesWebServices.Controllers;
public class AirportController : Controller
{
    private readonly IAirportService _airportService;
    public AirportController(IAirportService airportService)
    {
        _airportService = airportService;
    }

    // GET: AirportController
    public ActionResult Index(string searchTerm, string selectedOption)
    {
        try
        {
            if (!string.IsNullOrEmpty(searchTerm) && !string.IsNullOrEmpty(selectedOption))
            {
                List<Airport> airports = _airportService.GetAirportsByFilter(searchTerm, selectedOption);
                return View(airports);
            }
            else
            {
                List<Airport> airports = _airportService.GetAirports();
                return View(airports);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(new List<Airport>());
        }
    }

    [HttpPost]
    public ActionResult Index(Airport airport)
    {
        try
        {
            _airportService.AddAirport(airport);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(nameof(Index));
        }
    }

    public ActionResult Search()
    {
        return PartialView();
    }
}

Airlines.Web/Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;

using AirlinesWebServices.Models;
using AirlinesWebServices.Services;

namespace AirlinesWebServices.Controllers;
public class FlightController : Controller
{
    private readonly IFlightService _flightService;
    public FlightController(IFlightService flightService)
    {
        _flightService = flightService;
    }
    // GET: FlightController
    public ActionResult Index(string searchTerm, string selectedOption)
    {
        try
        {
            if (!string.IsNullOrEmpty(searchTerm) && !string.IsNullOrEmpty(selectedOption))
            {
                List<Flight> flights = _flightService.GetFlightsByFilter(searchTerm, selectedOption);
                return View(flights);
            }
            else
            {
                List<Flight> flights = _flightService.GetFlights();
                return View(flights);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(new List<Flight>());
        }
    }

    [HttpPost]
    public ActionResult Index(Flight flight)
    {
        try
        {
            _flightService.AddFlight(flight);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return View(nameof(Index));
        }
    }

    public ActionResult Search()
    {
        return PartialView();
    }
}

Airlines.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

using AirlinesPersistenceBasic.Repositories.Interfaces;
using Airlines.Web.Models;

namespace AirlinesWebServices.Controllers;
public class HomeController : Controller
{
    private readonly IAirportRepository _airportRepository;
    private readonly IAirlineRepository _airlineRepository;
    private readonly IFlightRepository _flightRepository;
#pragma warning disable IDE0052 // Remove unread private members
    private readonly ILogger<HomeController> _logger;
#pragma warning restore IDE0052 // Remove unread private members

    public HomeController(ILogger<HomeController> logger, IAirportRepository airportRepository, IAirlineRepository airlineRepository, IFlightRepository flightRepository)
    {
        _logger = logger;
        _airportRepository = airportRepository;
        _airlineRepository = airlineRepository;
        _flightRepository = flightRepository;
    }

    public IActionResult Index()
    {
        try
        {
            int airportsCount = _airportRepository.GetAirports().Count;
            int airlinesCount = _airlineRepository.GetAirlines().Count;
            int flightsCount = _flightRepository.GetFlights().Count;
            IndexViewModel indexViewModel = new IndexViewModel
            {
                AirlinesCount = airlinesCount,
                AirportsCount = airportsCount,
                FlightsCount = flightsCount
            };
            return View(indexViewModel);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            IndexViewModel indexViewModel = new IndexViewModel
            {
                AirlinesCount = 0,
                AirportsCount = 0,
                FlightsCount = 0
            };
            return View(indexViewModel);
        }

    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Airlines.Web/Views/Airline/Index.cshtml
@using AirlinesWebServices.Models
@model IEnumerable<AirlinesWebServices.Models.Airline>

@{
    ViewData["Title"] = "Airline";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    List<string> propertyList = typeof(Airline).GetProperties().Select(property => property.Name).Where(property => property != "Id").ToList();
}

<div class="main">
    <div class="main-header">
        <div class="main-header-arrow-image">
            <a asp-controller="Home" asp-action="Index"><img src="./assets/left sidebar.png" alt=""></a>
        </div>
        <div class="main-header-title">Airlines</div>
    </div>
    <div class="main-line"></div>
    <sectiion id="table-container">
    <partial>
      @await Html.PartialAsync("_Search", propertyList)
    </partial>
        <table class="main-table" id="main-table">
        <thead class="main-table-head">
            <tr>
                <th>Name</th>
                <th>Founded</th>
                <th>Fleet size</th>
                <th>Descriprion</th>
            </tr>
        </thead>
            <tbody class="main-table-body" id="main-table-body">
            @if (Model.Count() > 0)
            {

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Founded)</td>
                        <td>@Html.DisplayFor(modelItem => item.FleetSize)</td>
                        <td class="main-table-body-row">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">No airlines found</td>
                </tr>
            }
        </tbody>
    </table>
        <button id="main-show-all-table-button" onclick="toggleTableRows()">Show more</button>
    </sectiion>
    <button class="main-show-form-button" id="main-show-form-button" onclick="toggleViews()">Show form</button>
    <section id="form-container">
        <fieldset class="main-form">
            <legend>Add New Airline</legend>
            <form asp-action="Index" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="main-form-input-field">
                    @Html.Hidden("Id", new Airline())
                </div>
                <div class="main-form-input-field">
                    <label for="airline-name">Airline name</label>
                    <input type="text" name="Name" id="airline-name" required>
                    <div class="main-form-error-field" id="airline-name-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airline-founded">Founded</label>
                    <input type="date" value="2000-01-01" name="Founded" id="airline-founded" required>
                    <div class="main-form-error-field" id="airline-founded-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airline-fleet-size">Fleet size</label>
                    <input type="number" name="FleetSize" id="airline-fleet-size" required>
                    <div class="main-form-error-field" id="airline-fleet-size-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airline-description">Description</label>
                    <input type="text" name="Description" id="airline-description" required>
                    <div class="main-form-error-field" id="airline-description-error"></div>
                </div>
                <button type="submit" class="main-form-submit-button" id="main-form-submit-button">Submit</button>
            </form>
        </fieldset>
    </section>
</div>

Airlines.Web/Views/Airport/Index.cshtml
@using AirlinesWebServices.Models
@model IEnumerable<AirlinesWebServices.Models.Airport>

@{
    ViewData["Title"] = "Airport";
}

@{
    List<string> propertyList = typeof(Airport).GetProperties().Select(property => property.Name).Where(property => property != "Id").ToList();
}

<div class="main">
    <div class="main-header">
        <div class="main-header-arrow-image">
            <a asp-controller="Home" asp-action="Index"><img src="./assets/left sidebar.png" alt=""></a>
        </div>
        <div class="main-header-title">Airports</div>
    </div>
    <div class="main-line"></div>
    <section id="table-container">
    <partial>
        @await Html.PartialAsync("_Search", @propertyList)
    </partial>
        <table class="main-table" id="main-table">
        <thead class="main-table-head">
            <tr>
                <th>Name</th>
                <th>Country</th>
                <th>City</th>
                <th>Code</th>
                <th>Runways</th>
                <th>Founded</th>
            </tr>
        </thead>
            <tbody class="main-table-body" id="main-table-body">
            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RunwaysCount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Founded)
                        </td>
                    </tr>
                }
            }
            else
            {
             <tr>
                 <td colspan="6">No airports found</td>
             </tr>   
            }
            
        </tbody>
    </table>
        <button id="main-show-all-table-button" onclick="toggleTableRows()">Show more</button>
    </section>
    <button class="main-show-form-button" id="main-show-form-button" onclick="toggleViews()">Show form</button>
    <section id="form-container">
        <fieldset class="main-form">
            <legend>Add New Airport</legend>
            <form asp-action="Index" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="main-form-input-field">
                    @Html.Hidden("Id",new Airport())
                </div>
                <div class="main-form-input-field">
                    <label for="airport-name">Airport name</label>
                    <input type="text" name="Name" id="airport-name" required>
                    <div class="main-form-error-field" id="airport-name-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airport-country">Country</label>
                    <input type="text" name="Country" id="airport-country" required>
                    <div class="main-form-error-field" id="airport-country-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airport-city">City</label>
                    <input type="text" name="City" id="airport-city" required>
                    <div class="main-form-error-field" id="airport-city-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airport-code">Code</label>
                    <input type="text" name="Code" id="airport-code" required>
                    <div class="main-form-error-field" id="airport-code-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airport-runways-count">Runways count</label>
                    <input type="number" name="RunwaysCount" id="airport-runways-count" required>
                    <div class="main-form-error-field" id="airport-runways-count-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="airport-founded">Founded</label>
                    <input type="date" value="2000-01-01" name="Founded" id="airport-founded" required>
                    <div class="main-form-error-field" id="airport-founded-error"></div>
                </div>
            <button type="submit" class="main-form-submit-button" id="main-form-submit-button">Submit</button>
            </form>
           
        </fieldset>
    </section>
</div>

Airlines.Web/Views/Flight/Index.cshtml
@using AirlinesWebServices.Models
@model IEnumerable<AirlinesWebServices.Models.Flight>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    List<string> propertyList = typeof(Flight).GetProperties().Select(property => property.Name).Where(propertyList => propertyList != "Id").ToList();
}

<div class="main">
    <div class="main-header">
        <div class="main-header-arrow-image">
            <a asp-controller="Home" asp-action="Index"><img src="./assets/left sidebar.png" alt=""></a>
        </div>
        <div class="main-header-title">Flights</div>
    </div>
    <div class="main-line"></div>
    <section id="table-container">
        <partial>
            @await Html.PartialAsync("_Search", @propertyList)
        </partial>
        <table class="main-table" id="main-table">
            <thead class="main-table-head">
                <tr>
                    <th>Flight number</th>
                    <th>Airline</th>
                    <th>Depature airport</th>
                    <th>Arrival airport</th>
                    <th>Departure date & time</th>
                    <th>Arrival date & time</th>
                </tr>
            </thead>
            <tbody class="main-table-body" id="main-table-body">
                @if (Model.Count() > 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.FlightNumber)</td>
                            <td>@Html.DisplayFor(modelItem => item.AirlineName)</td>
                            <td>@Html.DisplayFor(modelItem => item.DepartureAirportName)</td>
                            <td>@Html.DisplayFor(modelItem => item.ArrivalAirportName)</td>
                            <td>@Html.DisplayFor(modelItem => item.DepartureDateTime)</td>
                            <td>@Html.DisplayFor(modelItem => item.ArrivalDateTime)</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6">No flights found</td>
                    </tr>
                }

            </tbody>
        </table>
        <button id="main-show-all-table-button" onclick="toggleTableRows()">Show more</button>
    </section>
    <button class="main-show-form-button" id="main-show-form-button" onclick="toggleViews()">Show form</button>
    <section id="form-container">
        <fieldset class="main-form">
            <legend>Add New Flight</legend>
            <form asp-action="Index" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="main-form-input-field">
                    @Html.Hidden("Id", new Flight())
                </div>
                <div class="main-form-input-field">
                    <label for="flight-flight-number">Flight number</label>
                    <input type="text" name="FlightNumber" id="flight-flight-number" required>
                    <div class="main-form-error-field" id="flight-flight-number-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="flight-airline-name">Airline</label>
                    <input type="text" name="AirlineName" id="flight-airline-name" required>
                    <div class="main-form-error-field" id="flight-airline-name-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="flight-departure-airport-name">Departure airport</label>
                    <input type="text" name="DepartureAirportName" id="flight-departure-airport-name" required>
                    <div class="main-form-error-field" id="flight-departure-airport-name-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="flight-arrival-airport-name">Arrival airport</label>
                    <input type="text" name="ArrivalAirportName" id="flight-arrival-airport-name" required>
                    <div class="main-form-error-field" id="flight-arrival-airport-name-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="flight-departure-date-time">Departure time</label>
                    <input type="datetime-local" value="2000-01-01T11:00" name="DepartureDateTime" id="flight-departure-date-time" required>
                    <div class="main-form-error-field" id="flight-departure-date-time-error"></div>
                </div>
                <div class="main-form-input-field">
                    <label for="flight-arrival-date-time">Arrival time</label>
                    <input type="datetime-local" value="2000-01-01T11:00" name="ArrivalDateTime" id="flight-arrival-date-time" required>
                    <div class="main-form-error-field" id="flight-arrival-date-time-error"></div>
                </div>
                <button type="submit" class="main-form-submit-button" id="main-form-submit-button">Submit</button>
            </form>
        </fieldset>
    </section>
</div>

Airlines.Web/Views/Home/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div id="index-main">
    <div class="main-text">Welcome To Dashboard</div>
    <div class="main-info-container">
        <div class="main-info-card">
            <div class="main-info-card-content">
                <div>Airports</div>
                <img src="./assets/mdi_airport.png" />
                <div>@Model.AirlinesCount</div>
            </div>
            <a asp-controller="Airport" asp-action="Index" class="main-info-card-link">Add New Airport</a>
        </div>
        <div class="main-info-card">
            <div class="main-info-card-content">
                <div>Airlines</div>
                <img src="./assets/ri_plane-fill.png" />
                <div>@Model.AirportsCount</div>
            </div>
            <a asp-controller="Airline" asp-action="Index" class="main-info-card-link">Add New Airline</a>
        </div>
        <div class="main-info-card">
            <div class="main-info-card-content">
                <div>Flights</div>
                <img src="./assets/carbon_flight-schedule.png" />
                <div>@Model.FlightsCount</div>
            </div>
            <a asp-controller="Flight" asp-action="Index" class="main-info-card-link">Add New Flight</a>
        </div>

    </div>
</div>

Airlines.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rise Airlines</title>
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <script src="~/js/buttonEvents.js" async defer></script>
    <script src="~/js//validation.js" async defer></script>
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navigation")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">Rise Airlines 2024 &#169;</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Airlines.Web/Views/Shared/_Navigation.cshtml
<nav class="navbar">
    <div class="navbar-title">
        Rise Airlines
        <img src="~/assets/header-plane.png" class="navbar-image" />
    </div>
    <ul class="navbar-links">
        <li><a asp-controller="Airport" asp-action="Index">Airports</a></li>
        <li><a asp-controller="Airline" asp-action="Index">Airlines</a></li>
        <li><a asp-controller="Flight" asp-action="Index">Flights</a></li>
    </ul>
</nav>

Airlines.Web/Views/Shared/_Search.cshtml
@model IEnumerable<string>

<div class="serachbar-container">
    <form method="get">
        <input type="text" name="searchTerm" placeholder="Search..." class="searchbar-input">
        <select name="selectedOption" class="searchbar-filter">
            @foreach (var property in Model)
            {
                if (@property != "Id")
                {
                    <option value="@property">@property</option>
                }
            }
        </select>
        <button type="submit" class="searchbar-button">Search</button>
        <button asp-action="Index" class="searchbar-button">Reset</button>
    </form>
</div>